// Import the createPlan function from the plan.js module and assign it's return value to the yearlyPlan variable
import { createPlan } from "../scripts/plan.js";
const yearlyPlan = createPlan();
// console.log(yearlyPlan)

// Create a seed object to test the ouput of the addPlant()
// const testSeed = {type: "grass", height: 200, output: 300};
// import { addPlant } from "./field.js";
import { usePlants } from "./field.js";
import { plantSeeds } from "./tractor.js";
import { harvestPlants } from "./harvester.js";
import { catalog } from "./catalog.js";
// allseed contains the array of all the plants from the field module
//  Assign the return value from the usePlants function to a new variable and invoke the function
const allSeed = usePlants();
// Import and invoke the plantSeeds function from tractor.js
// Calling plantSeeds with the yearlyPlan argument to be able to replace the parameter of plans with yearlyPlan which = createPlan()
plantSeeds(yearlyPlan);

// Calling the harvestPlants() and passing the argument of the output from the usePlants()
// harvestPlants() contains the array of plants
harvestPlants(allSeed);

let plantsForSale = harvestPlants(allSeed);
// calling the catalog() and giving it the argument of the array generated by the harvestPlants()
catalog(plantsForSale);
// console.log(catalog(plantsForSale))
// console.log(harvestPlants(allSeed))
//  console.log(allSeed);
// console.log(yearlyPlan)

// console.log(harvestPlants(usePlants()))
// console.log("Welcome to the main module")
// console.log(plantsForSale)
